site_name: XConn Docs
repo_url: https://github.com/xconnio
edit_uri: https://github.com/xconnio/xconn-docs/edit/main/docs/
repo_name: GitHub
site_author: XConnIO Ltd.
site_url: https://xconn.dev
site_dir: site

nav:
  - Overview: index.md
  - NXT Router: nxt.md
  - Tutorial: tutorial.md
  - Language Guides:
      - Dart: language-guides/dart.md
      - Go: language-guides/go.md
      - JavaScript: language-guides/javascript.md
      - Kotlin: language-guides/kotlin.md
      - Python: language-guides/python.md
      - Rust: language-guides/rust.md
      - Swift: language-guides/swift.md

theme:
  name: material
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracks
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://discord.gg/Yzw9krsW2n

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2025 <a href="https://github.com/xconnio"  target="_blank" rel="noopener">XConnIO Ltd.</a>
