site_name: XConn
nav:
  - Overview: index.md
  - Tutorial: tutorial.md
  - Language Guides:
      - Go: language-guides/go.md
      - Python: language-guides/python.md
      - Dart: language-guides/dart.md
      - Swift: language-guides/swift.md

theme:
  name: material
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracks
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

repo_url: https://github.com/xconnio
repo_name: xconnio
site_author: omer
site_url: https://xconn.dev
site_dir: site/docs

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/xconnio

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2025 <a href="https://github.com/xconnio"  target="_blank" rel="noopener">XConnIO Ltd.</a>
